// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  expressionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'expressions',
    },
  ],
  toolbarSidebar: [
    {
      type: 'autogenerated',
      dirName: 'toolbar',
    },
  ],
};

export default sidebars;
